version: '3'
services:
  db:
    build:
      context: .
      dockerfile: scripts/mysql.Dockerfile
    ports:
      - "3306:3306"
  go:
    depends_on:
      - db
    build:
      context: .
      dockerfile: scripts/go.Dockerfile
    command: /go-rest-api
    volumes:
      - .:/app
    ports:
      - 8080:8080

